# permissions for end users to edit tcpingresses.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: tcpingress-editor-role
rules:
- apiGroups:
  - power.io.github.com
  resources:
  - tcpingresses
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - power.io.github.com
  resources:
  - tcpingresses/status
  verbs:
  - get
