# permissions for end users to view tcpingresses.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: tcpingress-viewer-role
rules:
- apiGroups:
  - power.io.github.com
  resources:
  - tcpingresses
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - power.io.github.com
  resources:
  - tcpingresses/status
  verbs:
  - get
